version: "3.7"

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    user: "0:0"
    ports:
      - "${SEARXNG_PORT:-8082}:8080"
    environment:
      BASE_URL: ${SEARXNG_BASE_URL:-"http://localhost:8082"}
      INSTANCE_NAME: ${SEARXNG_INSTANCE_NAME:-"SearXNG"}
    volumes:
      - searxng-data:/etc/searxng

volumes:
  searxng-data: