services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    group_add:
      - "984"
    volumes:
      - ${N8N_DATA_DIR}:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nas/n8n:/mnt/nas/n8n
    environment:
      - N8N_PORT=${N8N_PORT}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - N8N_BASIC_AUTH_ACTIVE=false
      - NODE_ENV=production
      - N8N_API_KEY=${N8N_API_KEY}
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=${WEBHOOK_URL}
      - TZ=${TZ}
      - NODE_FUNCTION_ALLOW_EXTERNAL=node-ssh
      - NODE_FUNCTION_ALLOW_BUILTIN=*
    networks:
      - npm_default

networks:
  npm_default:
    external: true
