version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "${PIHOLE_PORT:-8081}:80/tcp"
    environment:
      TZ: ${TZ:-"America/New_York"}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      DNSMASQ_LISTENING: ${PIHOLE_DNSMASQ_LISTENING:-local}
    volumes:
      - 'pihole_etc:/etc/pihole'
      - 'pihole_dnsmasq:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

volumes:
  pihole_etc:
  pihole_dnsmasq: