version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8080:80"
    environment:
      - DOMAIN=http://192.168.1.100:8080
      - SIGNUPS_ALLOWED=false
    networks:
      - vaultwarden_net

networks:
  vaultwarden_net:
    driver: bridge
