version: "3.8"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    expose:
      - "3000"

    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.example.com

    volumes:
      - /docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - npm_default

networks:
  npm_default:
    external: true