services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - ALLOW_SIGNUP=false
      - BASE_URL=${BASE_URL}
      - DB_ENGINE=sqlite
    volumes:
      - data:/app/data
    expose:
      - "9000"
    networks:
      - npm_default

volumes:
  data:

networks:
  npm_default:
    external: true
